'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, CalendarDays, ChevronLeft } from 'lucide-react'

const articles = [
  { slug: 'un-leadership-au-service-de-la-communaute', title: "Le Médecin-Chef Njimogna Loukouman Akim incarne un leadership avéré", date: '21 janvier 2026', image: '/blog-direction.jpg', excerpt: "Une visite à la formation hospitalière de Mataket met en lumière une vision de la médecine centrée sur l'écoute, l'accueil et la dignité du patient." },
  { slug: 'communique-officiel-du-medecin-chef', title: 'Communiqué officiel du Médecin-Chef', date: '29 juin 2025', image: '/blog-communique.jpg', excerpt: 'Le CMA de Koutaba-Mataket porte à la connaissance des populations de Koutaba et de ses environs un communiqué officiel.' },
  { slug: 'un-don-important-pour-le-cma-de-koutaba-mataket', title: 'Un important don remis au CMA de Koutaba-Mataket', date: '09 mai 2025', image: '/blog-don-1.jpg', excerpt: 'Le CMA de Koutaba-Mataket a reçu un important don de l’honorable Rainatou, parlementaire à l’Assemblée nationale du Cameroun.' },
  { slug: 'campagne-sensibilisation-drepanocytose', title: 'Campagne de sensibilisation sur la drépanocytose', date: '19 juin 2025', image: '/blog-equipe.jpg', excerpt: 'Le CMA de Koutaba-Mataket et l’Association Santé Rurale ont sensibilisé la communauté au dépistage et à la prise en charge de la drépanocytose.' },
  { slug: 'un-geste-de-solidarite-pour-les-patients', title: 'Un geste de solidarité pour les patients du CMA', date: '13 avril 2025', image: '/blog-don-2.jpg', excerpt: 'Près de 25 patients ont reçu une aide financière grâce à la générosité d’un groupe de jeunes du département du Noun.' },
  { slug: 'journee-scientifique-au-cma', title: 'Journée scientifique au CMA de Koutaba-Mataket', date: '15 septembre 2024', image: '/blog-equipe.jpg', excerpt: 'Une journée de formation continue consacrée à la grossesse extra-utérine, à la hernie inguinale étranglée et aux paramètres vitaux.' },
  { slug: 'campagne-de-sante-jeunesse-medicale-du-noun', title: 'Campagne de santé de la Jeunesse Médicale du Noun', date: '02 août 2026', image: '/blog-campagne-1.jpeg', excerpt: 'Le CMA a accueilli une campagne pluridisciplinaire proposant des consultations en cardiologie, ophtalmologie, médecine générale, chirurgie dentaire et kinésithérapie.' },
]

export default function BlogPage() {
  return <main><header className="site-header"><div className="container nav-wrap"><Link className="brand" href="/"><Image src="/cma-logo.jpeg" alt="Logo du CMA Koutaba-Mataket" width={62} height={62} className="logo" /><span><strong>CMA Koutaba-Mataket</strong><small>Centre Médical d&apos;Arrondissement</small></span></Link><nav className="nav"><Link href="/">Accueil</Link><Link href="/#services">Nos services</Link><Link href="/blog">Actualités</Link><Link className="nav-cta" href="/#contact">Nous contacter <ArrowRight size={16} /></Link></nav></div></header><section className="page-hero"><div className="container"><Link className="back-link" href="/"><ChevronLeft size={16} /> Retour à l&apos;accueil</Link><div className="eyebrow green">Actualités du CMA</div><h1>Nos articles &amp; communiqués</h1><p>Retrouvez les nouvelles, témoignages et informations officielles du CMA de Koutaba-Mataket.</p></div></section><section className="section blog-section"><div className="container blog-grid">{articles.map((article) => <article className="article-card" key={article.slug}><Link href={`/blog/${article.slug}`}><div className="article-image"><Image src={article.image} alt="" fill sizes="(max-width: 700px) 100vw, 540px" /></div><div className="article-body"><div className="article-date"><CalendarDays size={15} /> {article.date}</div><h2>{article.title}</h2><p>{article.excerpt}</p><span className="inline-link">Lire l&apos;article <ArrowRight size={16} /></span></div></Link></article>)}</div></section><footer className="footer"><div className="container copyright"><span>© {new Date().getFullYear()} CMA Koutaba-Mataket</span><span>Mataket · Koutaba · Cameroun</span></div></footer></main>
}
