import Image from 'next/image'
import Link from 'next/link'
import { ArrowLeft, CalendarDays } from 'lucide-react'

const posts = {
  'un-leadership-au-service-de-la-communaute': {
    title: "Centre Médical d'Arrondissement de Koutaba : le Médecin-Chef Njimogna Loukouman Akim incarne un leadership avéré",
    date: '21 janvier 2026', image: '/blog-direction.jpg',
    paragraphs: ["Ce mardi 20 janvier 2026, nous avons décidé de visiter la formation hospitalière de Mataket par Koutaba. À notre arrivée, nous sommes accueillis par quelques personnels sanitaires avec beaucoup d’honneur et d’enthousiasme.", "Le Médecin-Chef Njimogna Loukouman Akim s’est imposé depuis son arrivée dans cette formation sanitaire comme un modèle de médecin toujours à l’écoute de ses patients et de son personnel sanitaire.", "Pour le Docteur Njims, comme on l’appelle communément, l’accueil est le premier médicament qui soulage psychologiquement le patient avant toute prise en charge éventuelle. Le Docteur Njims continue de mettre l’être humain au centre de ses préoccupations car, pour lui, sauver des vies est la meilleure chose au monde.", "Cependant, nous avons fait un tour dans certaines chambres d’hospitalisation et grande a été notre surprise de constater que plusieurs malades se retrouvent avec des factures impayées bien qu’ayant déjà été pris en charge, voire recouvré leur santé. À la question de savoir ce qu’il en est véritablement de ces cas, le Docteur Njims nous rassure qu’il faut d’abord sauver des vies, même si après, d’autres patients partent sans plus revenir, ce qui sape vraiment les efforts consentis pour le bon fonctionnement de ce centre hospitalier.", "Après un échange cordial avec le Médecin-Chef du Centre Médical d’Arrondissement de Koutaba, le Docteur Njimogna Loukouman Akim, nous avons eu droit à un petit déjeuner consistant.", "Enfin, il faut noter que le Docteur Njims se dit déterminé à servir sérieusement la population car le malade, pour lui, est un patient et non un client.", "« Aux âmes bien nées, la valeur n’attend point le nombre des années »."], credit: 'Bafoussam, le 20/01/2026 — Bachirou Mboindi, Lecteur Social.'
  },
  'communique-officiel-du-medecin-chef': {
    title: 'Communiqué officiel du Médecin-Chef du CMA de Koutaba-Mataket', date: '29 juin 2025', image: '/blog-communique.jpg',
    paragraphs: ["Le Médecin-Chef du Centre Médical d’Arrondissement de Koutaba-Mataket porte à la connaissance des populations de Koutaba et ses environs qu’une femme âgée d’une cinquantaine d’années est arrivée le 28 juin 2025 en état d’inconscience aux environs de 17h04, transportée par les gendarmes de la Brigade de Koutaba.", "À son arrivée, le Médecin-Chef a fait les examens physiques qui ont révélé un état de coma, de multiples lésions superficielles de type égratignures, des tuméfactions du dos et des membres inférieurs et une flaccidité dans les zones de déclive. Après les examens physiques et un bilan adéquat, elle a été mise sous soins en attendant de faire un scanner le lendemain et de préconiser une référence pour une meilleure prise en charge. Malheureusement, la dame a rendu l’âme à 4h48 malgré les efforts consentis.", "Aucun membre de la famille ne s’est présenté jusqu’au transport du corps sans vie, aux environs de 12h25, par la municipalité de Koutaba, ce dimanche 29 juin 2025.", "Le Médecin-Chef tient à informer le public que la dame en question, décédée ce jour à 4h48, s’était déjà rendue au CMA de Koutaba-Mataket le 18 février 2025 aux environs de 22h, se dirigeant vers la maternité pour s’installer dans une salle post-partum avant d’être expulsée par le personnel.", "Nous invitons toutes personnes connaissant cette femme à bien vouloir se diriger vers la Morgue de l’Hôpital Régional Annexe de Foumban pour recouper le corps. Le Médecin-Chef adresse ses condoléances à la famille éprouvée et regrette cette perte en vie humaine."], credit: 'Fait à Mataket, le 29 juin 2025 — Le Médecin-Chef.'
  },
  'un-don-important-pour-le-cma-de-koutaba-mataket': {
    title: 'Un important don remis au CMA de Koutaba-Mataket', date: '09 mai 2025', image: '/blog-don-1.jpg',
    paragraphs: ["Le CMA de Koutaba-Mataket a reçu ce vendredi 09 mai 2025 un important don de l’honorable Rainatou, parlementaire à l’Assemblée nationale du Cameroun.", "Le Médecin-Chef, Dr Njimogna Akim, également connu sous le nom de Doctor Njims, a exprimé sa reconnaissance à l’honorable députée pour ce geste important en faveur de la formation sanitaire et des populations de Koutaba-Mataket.", "À cette occasion, le Médecin-Chef a précisé que le CMA restera toujours ouvert à tout don provenant de toute personne ou organisation, sans aucune coloration politique ou religieuse. Ces contributions permettent de renforcer les capacités du centre et d’améliorer la qualité de la prise en charge des patients.", "Le Maire de la Commune de Koutaba a également accompagné ce don d’une enveloppe de 20 000 F CFA destinée à l’achat de carburant pour le groupe électrogène. Ce soutien contribue à maintenir la continuité des services essentiels au sein du centre médical.", "Le CMA de Koutaba-Mataket adresse ses sincères remerciements à l’honorable Rainatou, au Maire de la Commune de Koutaba et à toutes les personnes qui œuvrent pour renforcer les soins de santé au bénéfice de la communauté."],
    credit: 'Publié le 09 mai 2025 — CMA de Koutaba-Mataket.',
    gallery: ['/blog-don-2.jpg', '/blog-don-3.jpg', '/blog-don-4.jpg', '/blog-don-5.jpg', '/blog-don-6.jpg']
  },
  'campagne-sensibilisation-drepanocytose': {
    title: 'Campagne de sensibilisation sur la drépanocytose', date: '19 juin 2025', image: '/blog-equipe.jpg',
    paragraphs: ["Le CMA de Koutaba-Mataket, en collaboration avec l’Association Santé Rurale, a organisé une campagne de sensibilisation consacrée à la drépanocytose.", "Cette initiative a permis d’expliquer l’importance du test d’électrophorèse de l’hémoglobine, notamment pour connaître son statut et mieux prévenir les complications liées à la maladie.", "Les participants ont également reçu des conseils pratiques sur les comportements à adopter lorsqu’un enfant vit avec la drépanocytose : suivi médical régulier, bonne hydratation, prévention des infections et consultation rapide en cas de signes inhabituels."],
    credit: 'Publié le 19 juin 2025 — CMA de Koutaba-Mataket et Association Santé Rurale.'
  },
  'un-geste-de-solidarite-pour-les-patients': {
    title: 'Un geste de solidarité pour les patients du CMA', date: '13 avril 2025', image: '/blog-don-2.jpg',
    paragraphs: ["Le CMA de Koutaba-Mataket a reçu un groupe de jeunes mandaté par un autre jeune du département du Noun, venu apporter un soutien concret aux patients de la formation sanitaire.", "Environ 25 patients ont reçu chacun une somme de 20 000 francs CFA. Ce geste de solidarité a profondément touché les bénéficiaires et l’ensemble du personnel du CMA.", "Les patients ont chargé l’équipe de transmettre leurs sincères remerciements à ce bienfaiteur, désigné par les initiales AB, ainsi qu’à ses amis venus leur porter secours. Que Dieu les bénisse."],
    credit: 'Publié le 13 avril 2025 — CMA de Koutaba-Mataket.',
    gallery: ['/blog-don-3.jpg', '/blog-don-4.jpg']
  },
  'journee-scientifique-au-cma': {
    title: 'Journée scientifique au CMA de Koutaba-Mataket', date: '15 septembre 2024', image: '/blog-equipe.jpg',
    paragraphs: ["Le CMA de Koutaba-Mataket a organisé une journée de formation continue destinée à renforcer les compétences de son personnel et à améliorer la qualité de l’accueil et des soins.", "Les échanges ont porté sur la grossesse extra-utérine, les actes à réaliser à l’accueil face à une hernie inguinale étranglée, ainsi que sur les paramètres vitaux et les sites de prise de la tension artérielle, de la fréquence cardiaque, de la fréquence respiratoire et de la température.", "Les différents thèmes ont été présentés respectivement par Dr Gabin, Monsieur Mounjoupou Henri, Major du Bloc Opératoire, et Madame Dogmo Géraldine, Major PEV, sous la supervision de Dr Njimogna L. Akim, Médecin-Chef du CMA de Koutaba-Mataket.", "Une prochaine journée scientifique était annoncée pour le mardi 17 septembre 2024 sur le diabète sucré et les valeurs normales des paramètres vitaux."],
    credit: 'Publié le 15 septembre 2024 — #CMAMataket #CMAKoutabaMataket #Diabète #GEU #HernieInguinale.'
  },
  'campagne-de-sante-jeunesse-medicale-du-noun': {
    title: 'Campagne de santé de la Jeunesse Médicale du Noun', date: '02 août 2026', image: '/blog-campagne-1.jpeg',
    paragraphs: ["Le CMA de Koutaba-Mataket a abrité une campagne de santé organisée par la Jeunesse Médicale du Noun du 02 au 09 août 2026 dans l’arrondissement de Koutaba.", "Cette campagne pluridisciplinaire a proposé des consultations et des activités dans plusieurs spécialités, notamment la cardiologie, l’ophtalmologie, la médecine générale, la chirurgie dentaire, la kinésithérapie, l’imagerie et le laboratoire.", "À travers cette mobilisation, les professionnels de santé et les jeunes bénévoles ont rapproché les soins des populations et renforcé la sensibilisation autour de la prévention et du dépistage."],
    credit: 'Campagne organisée du 02 au 09 août 2026 — Jeunesse Médicale du Noun.',
    gallery: ['/blog-campagne-2.jpeg', '/blog-campagne-3.jpeg']
  }
} as const

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const post = posts[slug as keyof typeof posts]
  if (!post) return <main className="not-found"><h1>Article introuvable</h1><Link href="/blog">Retour aux articles</Link></main>
  return <main><header className="site-header"><div className="container nav-wrap"><Link className="brand" href="/"><Image src="/cma-logo.jpeg" alt="Logo du CMA Koutaba-Mataket" width={62} height={62} className="logo" /><span><strong>CMA Koutaba-Mataket</strong><small>Centre Médical d&apos;Arrondissement</small></span></Link><nav className="nav"><Link href="/">Accueil</Link><Link href="/blog">Actualités</Link><Link className="nav-cta" href="/#contact">Nous contacter</Link></nav></div></header><article className="article-detail"><div className="container article-container"><Link href="/blog" className="back-link"><ArrowLeft size={16} /> Tous les articles</Link><div className="article-detail-meta"><CalendarDays size={16} /> Publié le {post.date}</div><h1>{post.title}</h1><div className="article-detail-image"><Image src={post.image} alt="" fill priority sizes="(max-width: 900px) 100vw, 900px" /></div><div className="article-content">{post.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<p className="article-credit">{post.credit}</p>{'gallery' in post && <div className="article-gallery">{post.gallery.map((image, index) => <div className="gallery-image" key={image}><Image src={image} alt={`Photo ${index + 1} de la remise du don au CMA`} fill sizes="(max-width: 735px) 100vw, 360px" /></div>)}</div>}</div></div></article><footer className="footer"><div className="container copyright"><span>© {new Date().getFullYear()} CMA Koutaba-Mataket</span><span>Mataket · Koutaba · Cameroun</span></div></footer></main>
}
